### 예외발생 throw

- 예외를 정의하는 throw키워드

```c
#include<stdio.h>

class FileCreattionError {

};

void SaveToFile() {
	throw FileCreattionError(); // 예외를 던진다 즉 무조건 예외가 발생한다
}

void main() {
	SaveToFile();
}
```

### 예외처리 try-catch

- 예외가 발생하면 예외를 처리하는 코드 try-catch문을 사용
- catch(...)을 사용하면 모든 예외를 처리한다

```c
try { 
		SaveToFile();
	}
	catch (...) { //모든 예외를 처리
		printf("cannot create file!\n");
		return;
	}
```

- 파일을 오픈하지 못했을 때만 예외를 발생하도록하는 코드

```c
#include<stdio.h>

class FileCreattionError {

};

void SaveToFile() {
	File* fp;
	fp = fopen("a.dat", "wt");
	if(!fp) //fp가 비어있으면 예외발생
		throw FileCreattionError();
}

void main() {
	try { // SaveToFile 를 실행하고 예외가 발생한다면
		SaveToFile();
	}
	catch (FileCreattionError) { //해당 예외클래스가 발생하면 예외처리를 실행한다
		printf("cannot create file!\n");
		return;
	}
}
```

```c
#include<stdio.h>

class FileCreattionError {

};
class FileReadError {

};
void SaveToFile() {
	File* fp;
	fp = fopen("a.dat", "wt");
	if(!fp)
		throw FileCreattionError();
}
void ReaFromFile() {
	File* fp;
	fp = fopen("a.dat", "rt");
	if (!fp)
		throw FileReadError();
}
void main() {
	try {
		SaveToFile();
		ReaFromFile();
	}
	catch (FileCreattionError) {
		printf("cannot create file!\n");
		return;
	}
	catch (FileReadError) {
		printf("Cannot read file!\n");
		return;
	}
}
```

- 위 코드를 추상화

```c
#include<stdio.h>

class CFile {
public:
	class FileCreattionError {

	};
	class FileReadError {

	};
	class MemoryAllocError {

	};
	void SaveToFile() {
		File* fp;
		fp = fopen("a.dat", "wt");
		if (!fp)
			throw FileCreattionError();
	}

	void ReaFromFile() {
		File* fp;
		fp = fopen("a.dat", "rt");
		if (!fp)
			throw FileReadError();
	}
};

void main() {
	CFile gildong;
	try {
		gildong.SaveToFile();
		gildong.ReaFromFile();
	}
	catch (CFile::FileCreattionError) {
		printf("cannot create file!\n");
		return;
	}
	catch (CFile::FileReadError) {
		printf("Cannot read file!\n");
		return;
	}
}
```

### 예외통합

```c
#include<stdio.h>

class CFile {
public:
	int m_iType;

	FileError(int type) {
		m_iType = type;
	}
	void SaveToFile() {
		File* fp;
		fp = fopen("a.dat", "wt");
		if (!fp)
			throw FileError(1);
	}

	void ReaFromFile() {
		File* fp;
		fp = fopen("a.dat", "rt");
		if (!fp)
			throw FileError(2);
	}
};

void main() {
	CFile gildong;
	try {
		gildong.SaveToFile();
		gildong.ReaFromFile();
	}
	catch (CFile::FileError e) {
		if (e.m_iType == 0) {
			printf("Cannot create file!\n");
		}
		else if (e.m_iType == 1) {
			printf("Cannot read file!\n");
		}
		return;
	}
}
```

### terminate함수

- 발생한 예외를 처리하지 않을 경우 terminate함수가 자동으로 실행된다

```c
#include<stdio.h>
#include<eh.h> //다음 헤더 파일을 반드시 포함

class SomeError {

};

void Function() {
	throw SomeError();
}

void MyExceptionHandler() {
	printf("default exception handler!\n");
}

void main() {
	set_terminate(MyExceptionHandler);

	Function(); // 여기에서 예외 발생하나 처리되지는 않음
}
```